//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicAdd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSize
    {
        public int Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public string Size_Name { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
